### ISSUE TITLE
[FIXED] Do not define a valid '.' target

### ISSUE THREAD

**Issue by martineboh** [pantharshit00/prisma-docs-generator#12]
I am getting **\AppData\Roaming\npm-cache\_npx\16448\node_modules\prisma-docs-generator\node_modules\kleur' do not define a valid '.' target** whenever I run `npx prisma-docs-generator serve` and during `npx prisma generate`

Prisma 2.4.1

**Comment by pantharshit00** [comment]
Hey Martin,

Can you please tell me which terminal are you using? cmd or some other terminal?

**Comment by martineboh** [comment]
I use VSCode Integrated terminal and also Hyper.app

**Comment by martineboh** [comment]
It's FIXED! This issue is related to [https://github.com/postcss/autoprefixer/issues/1328](https://github.com/postcss/autoprefixer/issues/1328). I updated nodejs to version 14 and autoprefixer as stated in the link posted and it worked.

**Comment by martineboh** [comment]
I am closing this issue as updating nodejs >= 14 and autoprefixer@9.8.0 fixed it.
