### ISSUE TITLE
Unknown arg `is` and `isNot`

### ISSUE THREAD

**Issue by heymartinadams** [pantharshit00/prisma-docs-generator#13]
Been using your docs generator for complex nested queries, and so far super helpful! Came across the following error.

## My query
```js
const users = await prisma.user.findMany({
  where: {
    participants: {
      some: {
        registrations: {
          some: {
            eventOption: {
              is: {
                eventId: req.body.eventId
              }
            }
          }
        }
      }
    }
  }
})
```

Your doc says for `eventOption`:
![image](https://user-images.githubusercontent.com/11673745/90592759-32ff6400-e19b-11ea-8100-b4ba80c31d7f.png)

Terminal output:
![image](https://user-images.githubusercontent.com/11673745/90592791-47dbf780-e19b-11ea-8a3d-e0322fe8e355.png)

Not sure how to query this. I want to find `users` who `participate` in events who have `registered` for `event options` of a particular `event`.

**Comment by pantharshit00** [comment]
Hey @heymartinadams 

Thanks for reporting this. Looks like this field is only protocol level. I need to filter it out.
