### ISSUE TITLE
[feat] Summary of models at top

### ISSUE THREAD

**Issue by heymartinadams** [pantharshit00/prisma-docs-generator#15]
Hi @pantharshit00!

What do you think of adding a summary of all models at the top of page, with click-through links to each model?

![image](https://user-images.githubusercontent.com/11673745/92283169-2aee3680-eeb4-11ea-9945-c4bbd5dfa8a5.png)

We have a lot of models, so sometimes quite a bit of scrolling is needed to get to the relevant docs for a particular model.

**Comment by pantharshit00** [comment]
Sounds good, I can look into this when I will get some time.

**Comment by sonylomo** [comment]
Hey @pantharshit00, I'd like to help out with this issue. 🙂
