### ISSUE TITLE
hosting is not working [bug]

### ISSUE THREAD

**Issue by dankolesnikov** [pantharshit00/prisma-docs-generator#48]
- successfully installed and generated doc
After running `npx prisma-docs-generator serve` getting the following:
```
env: node\r: No such file or directory
```
After running `node node_modules/prisma-docs-generator` getting empty return, no printout - seems like its hanging. Nothing is at `http://localhost:5858/`.

**Comment by raarts** [comment]
I ran `find . -type f | xargs dos2unix` in the dist directory to fix this.

**Comment by pantharshit00** [comment]
I can republish this package with my Mac. 

This will eventually need a proper CI setup.

**Comment by Markkos89** [comment]
Having the same issue in a WSL2 ubuntu 22 console

**Comment by pantharshit00** [comment]
This should be addressed in the latest release.
