### ISSUE TITLE
Generated HTML has styling issue

### ISSUE THREAD

**Issue by ajhollowayvrm** [pantharshit00/prisma-docs-generator#51]
<img width="1512" alt="Screen Shot 2022-02-24 at 4 33 48 PM" src="https://user-images.githubusercontent.com/17866033/155625353-c1a3df35-399b-4a3f-bf81-67ee5130d591.png">

This is what I get. Any help?

**Comment by jiscsander** [comment]
@ajhollowayvrm did you find a solution? I'm getting the same issue.
