### ISSUE TITLE
Docs should specify to be a dev dependency

### ISSUE THREAD

**Issue by imMatheus** [pantharshit00/prisma-docs-generator#67]
In the instructions on installation, `npm install prisma-docs-generator` should be `npm install -D prisma-docs-generator`.

There is no need for this dependency to not be a dev dependency.

**Comment by pantharshit00** [comment]
Closed via https://github.com/pantharshit00/prisma-docs-generator/commit/52068885356022f8a62b1ce92090c2cb4d34349b
